#!usr/bin/python
# -*- coding: utf-8  -*-
#
# (C) Legoktm 2008-2009, MIT License
# 
import vitalarticles
import sys, os
sys.path.append(os.environ['HOME'] + '/stuffs/pywiki/pywikipedia')
import wikipedia
# Artists", finaltext)
site = wikipedia.getSite()
vapage = wikipedia.Page(site, 'Wikipedia:Vital articles')
starttext = vapage.get()
def unicodify(text):
	return text.encode('utf-8')
starttext = unicodify(starttext)
finaltext = vitalarticles.dp("Leonardo da Vinci", starttext)
finaltext = vitalarticles.dp("Michelangelo", finaltext)
finaltext = vitalarticles.dp("Rembrandt", finaltext)
#finaltext = vitalarticles.dp("Diego Velázquez", finaltext)
finaltext = vitalarticles.dp("Hokusai", finaltext)
finaltext = vitalarticles.dp("Claude Monet", finaltext)
finaltext = vitalarticles.dp("Vincent van Gogh", finaltext)
finaltext = vitalarticles.dp("Pablo Picasso", finaltext)
finaltext = vitalarticles.dp("Featured article Salvador Dalí", finaltext)
# Authors", finaltext)
finaltext = vitalarticles.dp("Homer", finaltext)
finaltext = vitalarticles.dp("Sophocles", finaltext)
finaltext = vitalarticles.dp("Virgil", finaltext)
finaltext = vitalarticles.dp("Li Bai", finaltext)
finaltext = vitalarticles.dp("Jalal ad-Din Muhammad Balkhi-Rumi", finaltext)
finaltext = vitalarticles.dp("Dante Alighieri", finaltext)
finaltext = vitalarticles.dp("Featured article William Shakespeare", finaltext)
finaltext = vitalarticles.dp("Miguel de Cervantes", finaltext)
finaltext = vitalarticles.dp("Molière", finaltext)
finaltext = vitalarticles.dp("Johann Wolfgang von Goethe", finaltext)
finaltext = vitalarticles.dp("Featured article Edgar Allan Poe", finaltext)
finaltext = vitalarticles.dp("Fyodor Dostoevsky", finaltext)
finaltext = vitalarticles.dp("Leo Tolstoy", finaltext)
finaltext = vitalarticles.dp("Featured article James Joyce", finaltext)
finaltext = vitalarticles.dp("Franz Kafka", finaltext)
finaltext = vitalarticles.dp("Pablo Neruda", finaltext)
# Composers and musicians", finaltext)
finaltext = vitalarticles.dp("Johann Sebastian Bach", finaltext)
finaltext = vitalarticles.dp("Wolfgang Amadeus Mozart", finaltext)
finaltext = vitalarticles.dp("Ludwig van Beethoven", finaltext)
finaltext = vitalarticles.dp("Frédéric Chopin", finaltext)
finaltext = vitalarticles.dp("Richard Wagner", finaltext)
finaltext = vitalarticles.dp("Louis Armstrong", finaltext)
finaltext = vitalarticles.dp("Igor Stravinsky", finaltext)
finaltext = vitalarticles.dp("Elvis Presley", finaltext)
finaltext = vitalarticles.dp("The Beatles", finaltext)
# Explorers", finaltext)
finaltext = vitalarticles.dp("Roald Amundsen", finaltext)
finaltext = vitalarticles.dp("Jacques Cartier", finaltext)
finaltext = vitalarticles.dp("Christopher Columbus", finaltext)
finaltext = vitalarticles.dp("James Cook", finaltext)
finaltext = vitalarticles.dp("C-class article Ferdinand Magellan", finaltext)
finaltext = vitalarticles.dp("Marco Polo", finaltext)
finaltext = vitalarticles.dp("Ibn Battuta", finaltext)
finaltext = vitalarticles.dp("Zheng He", finaltext)
# Inventors and scientists", finaltext)
finaltext = vitalarticles.dp("Nicolaus Copernicus", finaltext)
finaltext = vitalarticles.dp("Featured article Charles Darwin", finaltext)
finaltext = vitalarticles.dp("Thomas Edison", finaltext)
finaltext = vitalarticles.dp("Albert Einstein", finaltext)
finaltext = vitalarticles.dp("Galileo Galilei", finaltext)
finaltext = vitalarticles.dp("Geber", finaltext)
finaltext = vitalarticles.dp("Carl Linnaeus", finaltext)
finaltext = vitalarticles.dp("Featured article Isaac Newton", finaltext)
finaltext = vitalarticles.dp("Nikola Tesla", finaltext)
finaltext = vitalarticles.dp("Sigmund Freud", finaltext)
finaltext = vitalarticles.dp("Niels Bohr", finaltext)
finaltext = vitalarticles.dp("Marie Curie", finaltext)
finaltext = vitalarticles.dp("Dmitri Mendeleev", finaltext)
# Mathematicians", finaltext)
finaltext = vitalarticles.dp("Featured article Archimedes", finaltext)
finaltext = vitalarticles.dp("Euclid", finaltext)
finaltext = vitalarticles.dp("Featured article Leonhard Euler", finaltext)
finaltext = vitalarticles.dp("Carl Friedrich Gauss", finaltext)
finaltext = vitalarticles.dp("Kurt Gödel", finaltext)
finaltext = vitalarticles.dp("David Hilbert", finaltext)
finaltext = vitalarticles.dp("Gottfried Leibniz", finaltext)
finaltext = vitalarticles.dp("Featured article Blaise Pascal", finaltext)
finaltext = vitalarticles.dp("Henri Poincaré", finaltext)
finaltext = vitalarticles.dp("Pythagoras", finaltext)
finaltext = vitalarticles.dp("Alan Turing", finaltext)
finaltext = vitalarticles.dp("Muhammad ibn Mūsā al-Khwārizmī", finaltext)
# Philosophers and social scientists", finaltext)
finaltext = vitalarticles.dp("Confucius", finaltext)
finaltext = vitalarticles.dp("Socrates", finaltext)
finaltext = vitalarticles.dp("Plato", finaltext)
finaltext = vitalarticles.dp("Aristotle", finaltext)
finaltext = vitalarticles.dp("Nagarjuna", finaltext)
finaltext = vitalarticles.dp("Avicenna", finaltext)
finaltext = vitalarticles.dp("Thomas Aquinas", finaltext)
finaltext = vitalarticles.dp("Ibn Khaldun", finaltext)
finaltext = vitalarticles.dp("René Descartes", finaltext)
finaltext = vitalarticles.dp("John Locke", finaltext)
finaltext = vitalarticles.dp("Immanuel Kant", finaltext)
finaltext = vitalarticles.dp("Karl Marx", finaltext)
finaltext = vitalarticles.dp("Friedrich Nietzsche", finaltext)
finaltext = vitalarticles.dp("Featured article Max Weber", finaltext)
# Religious figures", finaltext)
finaltext = vitalarticles.dp("Abraham", finaltext)
finaltext = vitalarticles.dp("Gautama Buddha", finaltext)
finaltext = vitalarticles.dp("Guru Nanak Dev", finaltext)
finaltext = vitalarticles.dp("Jesus", finaltext)
finaltext = vitalarticles.dp("Laozi", finaltext)
finaltext = vitalarticles.dp("Moses", finaltext)
finaltext = vitalarticles.dp("Muhammad", finaltext)
finaltext = vitalarticles.dp("Paul the Apostle", finaltext)
finaltext = vitalarticles.dp("Zoroaster", finaltext)
# Politicians and leaders", finaltext)
finaltext = vitalarticles.dp("Hammurabi", finaltext)
finaltext = vitalarticles.dp("Cyrus the Great", finaltext)
finaltext = vitalarticles.dp("Alexander the Great", finaltext)
finaltext = vitalarticles.dp("Qin Shi Huang", finaltext)
finaltext = vitalarticles.dp("Julius Caesar", finaltext)
finaltext = vitalarticles.dp("Cleopatra VII", finaltext)
finaltext = vitalarticles.dp("Featured article Augustus", finaltext)
finaltext = vitalarticles.dp("C-class article Attila the Hun", finaltext)
finaltext = vitalarticles.dp("Charlemagne", finaltext)
finaltext = vitalarticles.dp("Genghis Khan", finaltext)
finaltext = vitalarticles.dp("Featured article Joan of Arc", finaltext)
finaltext = vitalarticles.dp("Featured article Suleiman the Magnificent", finaltext)
finaltext = vitalarticles.dp("Featured article Elizabeth I of England", finaltext)
finaltext = vitalarticles.dp("George Washington", finaltext)
finaltext = vitalarticles.dp("Napoleon I of France", finaltext)
finaltext = vitalarticles.dp("Simón Bolívar", finaltext)
finaltext = vitalarticles.dp("Abraham Lincoln", finaltext)
finaltext = vitalarticles.dp("Mustafa Kemal Atatürk", finaltext)
finaltext = vitalarticles.dp("Featured article Mohandas Karamchand Gandhi", finaltext)
finaltext = vitalarticles.dp("Vladimir Lenin", finaltext)
finaltext = vitalarticles.dp("Winston Churchill", finaltext)
finaltext = vitalarticles.dp("Joseph Stalin", finaltext)
finaltext = vitalarticles.dp("Adolf Hitler", finaltext)
finaltext = vitalarticles.dp("Mao Zedong", finaltext)
finaltext = vitalarticles.dp("Nelson Mandela", finaltext)
# History (60 articles)", finaltext)
finaltext = vitalarticles.dp("History", finaltext)
finaltext = vitalarticles.dp("Civilization", finaltext)
finaltext = vitalarticles.dp("History of the world", finaltext)
finaltext = vitalarticles.dp("History of Africa", finaltext)
finaltext = vitalarticles.dp("History of the Americas", finaltext)
finaltext = vitalarticles.dp("History of China", finaltext)
finaltext = vitalarticles.dp("History of Europe", finaltext)
finaltext = vitalarticles.dp("History of India", finaltext)
finaltext = vitalarticles.dp("History of Japan", finaltext)
finaltext = vitalarticles.dp("History of the Middle East", finaltext)
# Prehistory to Middle Ages", finaltext)
finaltext = vitalarticles.dp("Prehistory", finaltext)
finaltext = vitalarticles.dp("Stone Age", finaltext)
finaltext = vitalarticles.dp("Mesopotamia", finaltext)
finaltext = vitalarticles.dp("Neolithic Revolution", finaltext)
finaltext = vitalarticles.dp("Sumer", finaltext)
finaltext = vitalarticles.dp("Bronze Age", finaltext)
finaltext = vitalarticles.dp("Featured article Ancient Egypt", finaltext)
finaltext = vitalarticles.dp("Assyria", finaltext)
finaltext = vitalarticles.dp("Indus Valley Civilization", finaltext)
finaltext = vitalarticles.dp("Iron Age", finaltext)
finaltext = vitalarticles.dp("Ancient Greece", finaltext)
finaltext = vitalarticles.dp("Ancient Rome", finaltext)
finaltext = vitalarticles.dp("Macedon", finaltext)
finaltext = vitalarticles.dp("Persian Empire", finaltext)
finaltext = vitalarticles.dp("Middle Ages", finaltext)
finaltext = vitalarticles.dp("Black Death", finaltext)
finaltext = vitalarticles.dp("Featured article Byzantine Empire", finaltext)
finaltext = vitalarticles.dp("Crusades", finaltext)
finaltext = vitalarticles.dp("East-West Schism", finaltext)
finaltext = vitalarticles.dp("Holy Roman Empire", finaltext)
finaltext = vitalarticles.dp("Islamic Golden Age", finaltext)
finaltext = vitalarticles.dp("Mongol Empire", finaltext)
finaltext = vitalarticles.dp("Ottoman Empire", finaltext)
finaltext = vitalarticles.dp("Pre-Columbian", finaltext)
finaltext = vitalarticles.dp("Spanish Inquisition", finaltext)
finaltext = vitalarticles.dp("Viking Age", finaltext)
# Renaissance to present", finaltext)
finaltext = vitalarticles.dp("Abolitionism", finaltext)
finaltext = vitalarticles.dp("Age of Discovery", finaltext)
finaltext = vitalarticles.dp("Age of Enlightenment", finaltext)
finaltext = vitalarticles.dp("British Empire", finaltext)
finaltext = vitalarticles.dp("Civil rights movement", finaltext)
finaltext = vitalarticles.dp("Cold War", finaltext)
finaltext = vitalarticles.dp("Congress of Vienna", finaltext)
finaltext = vitalarticles.dp("Cultural Revolution", finaltext)
finaltext = vitalarticles.dp("European colonization of the Americas", finaltext)
finaltext = vitalarticles.dp("History of the European Union", finaltext)
finaltext = vitalarticles.dp("French Revolution", finaltext)
finaltext = vitalarticles.dp("Great Depression", finaltext)
finaltext = vitalarticles.dp("The Holocaust", finaltext)
finaltext = vitalarticles.dp("Industrial Revolution", finaltext)
finaltext = vitalarticles.dp("Iranian Revolution", finaltext)
finaltext = vitalarticles.dp("Korean War", finaltext)
finaltext = vitalarticles.dp("Napoleonic Wars", finaltext)
finaltext = vitalarticles.dp("Protestant Reformation", finaltext)
finaltext = vitalarticles.dp("Renaissance", finaltext)
finaltext = vitalarticles.dp("Russian Empire", finaltext)
finaltext = vitalarticles.dp("Scientific Revolution", finaltext)
finaltext = vitalarticles.dp("Scramble for Africa", finaltext)
finaltext = vitalarticles.dp("Soviet Union", finaltext)
finaltext = vitalarticles.dp("Space exploration", finaltext)
finaltext = vitalarticles.dp("Taiping Rebellion", finaltext)
finaltext = vitalarticles.dp("History of the United States", finaltext)
finaltext = vitalarticles.dp("Women's suffrage", finaltext)
finaltext = vitalarticles.dp("World War I", finaltext)
finaltext = vitalarticles.dp("World War II", finaltext)
# Geography (106 articles)", finaltext)
finaltext = vitalarticles.dp("Geography", finaltext)
finaltext = vitalarticles.dp("City", finaltext)
finaltext = vitalarticles.dp("Continent", finaltext)
finaltext = vitalarticles.dp("Country", finaltext)
finaltext = vitalarticles.dp("Desert", finaltext)
finaltext = vitalarticles.dp("Forest", finaltext)
finaltext = vitalarticles.dp("Glacier", finaltext)
finaltext = vitalarticles.dp("Mountain", finaltext)
finaltext = vitalarticles.dp("Ocean", finaltext)
finaltext = vitalarticles.dp("River", finaltext)
# Bodies of water", finaltext)
finaltext = vitalarticles.dp("Amazon River", finaltext)
finaltext = vitalarticles.dp("Atlantic Ocean", finaltext)
finaltext = vitalarticles.dp("Black Sea", finaltext)
finaltext = vitalarticles.dp("Caspian Sea", finaltext)
finaltext = vitalarticles.dp("Danube", finaltext)
finaltext = vitalarticles.dp("Great Barrier Reef", finaltext)
finaltext = vitalarticles.dp("Indian Ocean", finaltext)
finaltext = vitalarticles.dp("Mediterranean Sea", finaltext)
finaltext = vitalarticles.dp("Niagara Falls", finaltext)
finaltext = vitalarticles.dp("Nile", finaltext)
finaltext = vitalarticles.dp("Pacific Ocean", finaltext)
finaltext = vitalarticles.dp("Featured article Panama Canal", finaltext)
finaltext = vitalarticles.dp("Suez Canal", finaltext)
# Cities", finaltext)
finaltext = vitalarticles.dp("Athens", finaltext)
finaltext = vitalarticles.dp("Beijing", finaltext)
finaltext = vitalarticles.dp("Berlin", finaltext)
finaltext = vitalarticles.dp("Featured article Delhi", finaltext)
finaltext = vitalarticles.dp("Featured article Hong Kong", finaltext)
finaltext = vitalarticles.dp("Istanbul", finaltext)
finaltext = vitalarticles.dp("Featured article Jerusalem", finaltext)
finaltext = vitalarticles.dp("London", finaltext)
finaltext = vitalarticles.dp("Los Angeles", finaltext)
finaltext = vitalarticles.dp("Mecca", finaltext)
finaltext = vitalarticles.dp("Mexico City", finaltext)
finaltext = vitalarticles.dp("Moscow", finaltext)
finaltext = vitalarticles.dp("Featured article New York City", finaltext)
finaltext = vitalarticles.dp("Paris", finaltext)
finaltext = vitalarticles.dp("Rome", finaltext)
finaltext = vitalarticles.dp("São Paulo", finaltext)
finaltext = vitalarticles.dp("Seoul", finaltext)
finaltext = vitalarticles.dp("Tokyo", finaltext)
# Continents and regions", finaltext)
finaltext = vitalarticles.dp("Africa", finaltext)
finaltext = vitalarticles.dp("Featured article Antarctica", finaltext)
finaltext = vitalarticles.dp("Arctic", finaltext)
finaltext = vitalarticles.dp("Asia", finaltext)
finaltext = vitalarticles.dp("Europe", finaltext)
finaltext = vitalarticles.dp("Latin America", finaltext)
finaltext = vitalarticles.dp("Middle East", finaltext)
finaltext = vitalarticles.dp("North America", finaltext)
finaltext = vitalarticles.dp("Oceania", finaltext)
finaltext = vitalarticles.dp("South America", finaltext)
# Countries", finaltext)
finaltext = vitalarticles.dp("Argentina", finaltext)
finaltext = vitalarticles.dp("Featured article Australia", finaltext)
finaltext = vitalarticles.dp("Austria", finaltext)
finaltext = vitalarticles.dp("Featured article Bangladesh", finaltext)
finaltext = vitalarticles.dp("Featured article Belgium", finaltext)
finaltext = vitalarticles.dp("Brazil", finaltext)
finaltext = vitalarticles.dp("Burma", finaltext)
finaltext = vitalarticles.dp("Featured article Canada", finaltext)
finaltext = vitalarticles.dp("People's Republic of China", finaltext)
finaltext = vitalarticles.dp("Colombia", finaltext)
finaltext = vitalarticles.dp("Democratic Republic of the Congo", finaltext)
finaltext = vitalarticles.dp("Denmark", finaltext)
finaltext = vitalarticles.dp("Egypt", finaltext)
finaltext = vitalarticles.dp("Ethiopia", finaltext)
finaltext = vitalarticles.dp("Finland", finaltext)
finaltext = vitalarticles.dp("France", finaltext)
finaltext = vitalarticles.dp("Featured article Germany", finaltext)
finaltext = vitalarticles.dp("Greece", finaltext)
finaltext = vitalarticles.dp("Featured article India", finaltext)
finaltext = vitalarticles.dp("Featured article Indonesia", finaltext)
finaltext = vitalarticles.dp("Iran", finaltext)
finaltext = vitalarticles.dp("Iraq", finaltext)
finaltext = vitalarticles.dp("Republic of Ireland", finaltext)
finaltext = vitalarticles.dp("Featured article Israel", finaltext)
finaltext = vitalarticles.dp("Italy", finaltext)
finaltext = vitalarticles.dp("Featured article Japan", finaltext)
finaltext = vitalarticles.dp("Mexico", finaltext)
finaltext = vitalarticles.dp("Netherlands", finaltext)
finaltext = vitalarticles.dp("Nigeria", finaltext)
finaltext = vitalarticles.dp("Norway", finaltext)
finaltext = vitalarticles.dp("Featured article Pakistan", finaltext)
finaltext = vitalarticles.dp("Philippines", finaltext)
finaltext = vitalarticles.dp("Poland", finaltext)
finaltext = vitalarticles.dp("Russia", finaltext)
finaltext = vitalarticles.dp("Saudi Arabia", finaltext)
finaltext = vitalarticles.dp("Singapore", finaltext)
finaltext = vitalarticles.dp("Featured article South Africa", finaltext)
finaltext = vitalarticles.dp("South Korea", finaltext)
finaltext = vitalarticles.dp("Spain", finaltext)
finaltext = vitalarticles.dp("Sweden", finaltext)
finaltext = vitalarticles.dp("Switzerland", finaltext)
finaltext = vitalarticles.dp("Republic of China (Taiwan)", finaltext)
finaltext = vitalarticles.dp("Thailand", finaltext)
finaltext = vitalarticles.dp("Featured article Turkey", finaltext)
finaltext = vitalarticles.dp("Ukraine", finaltext)
finaltext = vitalarticles.dp("United Kingdom", finaltext)
finaltext = vitalarticles.dp("United States", finaltext)
finaltext = vitalarticles.dp("Vietnam", finaltext)
# Mountains, valleys and deserts", finaltext)
finaltext = vitalarticles.dp("Alps", finaltext)
finaltext = vitalarticles.dp("Andes", finaltext)
finaltext = vitalarticles.dp("Gobi Desert", finaltext)
finaltext = vitalarticles.dp("Grand Canyon", finaltext)
finaltext = vitalarticles.dp("Himalayas", finaltext)
finaltext = vitalarticles.dp("Mount Everest", finaltext)
finaltext = vitalarticles.dp("Sahara", finaltext)
# Arts and culture (56 articles)", finaltext)
finaltext = vitalarticles.dp("Art", finaltext)
finaltext = vitalarticles.dp("History of art", finaltext)
finaltext = vitalarticles.dp("Aesthetics", finaltext)
# Artistic movements", finaltext)
finaltext = vitalarticles.dp("Gothic", finaltext)
finaltext = vitalarticles.dp("Baroque", finaltext)
finaltext = vitalarticles.dp("Romanticism", finaltext)
finaltext = vitalarticles.dp("Modernism", finaltext)
finaltext = vitalarticles.dp("Postmodernism", finaltext)
finaltext = vitalarticles.dp("Pop culture", finaltext)
# Literature", finaltext)
finaltext = vitalarticles.dp("Literature", finaltext)
finaltext = vitalarticles.dp("History of literature", finaltext)
finaltext = vitalarticles.dp("Prose", finaltext)
finaltext = vitalarticles.dp("Book", finaltext)
finaltext = vitalarticles.dp("Fiction", finaltext)
finaltext = vitalarticles.dp("Novel", finaltext)
finaltext = vitalarticles.dp("Short story", finaltext)
finaltext = vitalarticles.dp("Featured article Poetry", finaltext)
finaltext = vitalarticles.dp("Rhyme", finaltext)
finaltext = vitalarticles.dp("Forms", finaltext)
finaltext = vitalarticles.dp("Epic poetry", finaltext)
finaltext = vitalarticles.dp("Haiku", finaltext)
finaltext = vitalarticles.dp("Sonnet", finaltext)
# Music", finaltext)
finaltext = vitalarticles.dp("Music", finaltext)
finaltext = vitalarticles.dp("History of music", finaltext)
finaltext = vitalarticles.dp("Musical instrument", finaltext)
finaltext = vitalarticles.dp("Singing", finaltext)
finaltext = vitalarticles.dp("Genres", finaltext)
finaltext = vitalarticles.dp("Classical music", finaltext)
finaltext = vitalarticles.dp("Folk music", finaltext)
finaltext = vitalarticles.dp("Hip hop music", finaltext)
finaltext = vitalarticles.dp("Jazz", finaltext)
finaltext = vitalarticles.dp("Pop music", finaltext)
finaltext = vitalarticles.dp("Rock music", finaltext)
# Performing arts", finaltext)
finaltext = vitalarticles.dp("Performing arts", finaltext)
finaltext = vitalarticles.dp("Dance", finaltext)
finaltext = vitalarticles.dp("Ballet", finaltext)
finaltext = vitalarticles.dp("Film", finaltext)
finaltext = vitalarticles.dp("Documentary", finaltext)
finaltext = vitalarticles.dp("Opera", finaltext)
finaltext = vitalarticles.dp("Orchestra", finaltext)
finaltext = vitalarticles.dp("Theatre", finaltext)
finaltext = vitalarticles.dp("Comedy", finaltext)
finaltext = vitalarticles.dp("Tragedy", finaltext)
# Visual arts", finaltext)
finaltext = vitalarticles.dp("Visual arts", finaltext)
finaltext = vitalarticles.dp("Architecture", finaltext)
finaltext = vitalarticles.dp("Seven Wonders of the Ancient World", finaltext)
finaltext = vitalarticles.dp("Great Wall of China", finaltext)
finaltext = vitalarticles.dp("Comics", finaltext)
finaltext = vitalarticles.dp("Drawing", finaltext)
finaltext = vitalarticles.dp("Painting", finaltext)
finaltext = vitalarticles.dp("Illustration", finaltext)
finaltext = vitalarticles.dp("Portrait", finaltext)
finaltext = vitalarticles.dp("Photography", finaltext)
finaltext = vitalarticles.dp("Sculpture", finaltext)
finaltext = vitalarticles.dp("Pottery", finaltext)
finaltext = vitalarticles.dp("Statue", finaltext)
# Philosophy and religion (77 articles)", finaltext)
# Philosophy", finaltext)
finaltext = vitalarticles.dp("Philosophy", finaltext)
finaltext = vitalarticles.dp("Philosophical branches", finaltext)
finaltext = vitalarticles.dp("Ethics", finaltext)
finaltext = vitalarticles.dp("Epistemology", finaltext)
finaltext = vitalarticles.dp("Belief", finaltext)
finaltext = vitalarticles.dp("Knowledge", finaltext)
finaltext = vitalarticles.dp("Truth", finaltext)
finaltext = vitalarticles.dp("Logic", finaltext)
finaltext = vitalarticles.dp("Metaphysics", finaltext)
finaltext = vitalarticles.dp("Existence", finaltext)
finaltext = vitalarticles.dp("Ontology", finaltext)
finaltext = vitalarticles.dp("Free will", finaltext)
finaltext = vitalarticles.dp("Philosophy by region and period", finaltext)
finaltext = vitalarticles.dp("Western philosophy", finaltext)
finaltext = vitalarticles.dp("Greek philosophy", finaltext)
finaltext = vitalarticles.dp("Medieval philosophy", finaltext)
finaltext = vitalarticles.dp("Contemporary philosophy", finaltext)
finaltext = vitalarticles.dp("Eastern philosophy", finaltext)
finaltext = vitalarticles.dp("Chinese philosophy", finaltext)
finaltext = vitalarticles.dp("Indian philosophy", finaltext)
finaltext = vitalarticles.dp("Islamic philosophy", finaltext)
finaltext = vitalarticles.dp("Philosophical movements", finaltext)
finaltext = vitalarticles.dp("Confucianism", finaltext)
finaltext = vitalarticles.dp("Existentialism", finaltext)
finaltext = vitalarticles.dp("Idealism", finaltext)
finaltext = vitalarticles.dp("Hedonism", finaltext)
finaltext = vitalarticles.dp("Humanism", finaltext)
finaltext = vitalarticles.dp("Marxism", finaltext)
finaltext = vitalarticles.dp("Nihilism", finaltext)
finaltext = vitalarticles.dp("Rationalism", finaltext)
finaltext = vitalarticles.dp("Realism", finaltext)
finaltext = vitalarticles.dp("Skepticism", finaltext)


# Religion", finaltext)

finaltext = vitalarticles.dp("Religion", finaltext)
finaltext = vitalarticles.dp("Deity", finaltext)
finaltext = vitalarticles.dp("God", finaltext)
finaltext = vitalarticles.dp("Goddess", finaltext)
finaltext = vitalarticles.dp("Mythology", finaltext)
finaltext = vitalarticles.dp("Mysticism", finaltext)
finaltext = vitalarticles.dp("Soul", finaltext)
finaltext = vitalarticles.dp("Spirituality", finaltext)
finaltext = vitalarticles.dp("Meditation", finaltext)
finaltext = vitalarticles.dp("Prayer", finaltext)
finaltext = vitalarticles.dp("Worship", finaltext)
finaltext = vitalarticles.dp("Yoga", finaltext)
finaltext = vitalarticles.dp("Theistic philosophies", finaltext)
finaltext = vitalarticles.dp("Theism", finaltext)
finaltext = vitalarticles.dp("Agnosticism", finaltext)
finaltext = vitalarticles.dp("Featured article Atheism", finaltext)
finaltext = vitalarticles.dp("Deism", finaltext)
finaltext = vitalarticles.dp("Gnosticism", finaltext)
finaltext = vitalarticles.dp("Pantheism", finaltext)

# Specific religions", finaltext)

finaltext = vitalarticles.dp("Featured article Bahá'í Faith", finaltext)
finaltext = vitalarticles.dp("Buddhism", finaltext)
finaltext = vitalarticles.dp("Mahayana", finaltext)
finaltext = vitalarticles.dp("Theravada", finaltext)
finaltext = vitalarticles.dp("Vajrayana", finaltext)
finaltext = vitalarticles.dp("Christianity", finaltext)
finaltext = vitalarticles.dp("Bible", finaltext)
finaltext = vitalarticles.dp("Christian Church", finaltext)
finaltext = vitalarticles.dp("Roman Catholic Church", finaltext)
finaltext = vitalarticles.dp("Eastern Orthodox Church", finaltext)
finaltext = vitalarticles.dp("Protestantism", finaltext)
finaltext = vitalarticles.dp("Pope", finaltext)
finaltext = vitalarticles.dp("Hinduism", finaltext)
finaltext = vitalarticles.dp("Bhagavad Gita", finaltext)
finaltext = vitalarticles.dp("Krishna", finaltext)
finaltext = vitalarticles.dp("Upanishads", finaltext)
finaltext = vitalarticles.dp("Vedas", finaltext)
finaltext = vitalarticles.dp("Featured article Islam", finaltext)
finaltext = vitalarticles.dp("Featured article Mosque", finaltext)
finaltext = vitalarticles.dp("Five pillars of Islam", finaltext)
finaltext = vitalarticles.dp("Divisions of Islam", finaltext)
finaltext = vitalarticles.dp("Qur'an", finaltext)
finaltext = vitalarticles.dp("Jainism", finaltext)
finaltext = vitalarticles.dp("Judaism", finaltext)
finaltext = vitalarticles.dp("Tanakh", finaltext)
finaltext = vitalarticles.dp("Shinto", finaltext)
finaltext = vitalarticles.dp("Featured article Sikhism", finaltext)
finaltext = vitalarticles.dp("Guru Granth Sahib", finaltext)
finaltext = vitalarticles.dp("Taoism", finaltext)
finaltext = vitalarticles.dp("Voodoo", finaltext)
finaltext = vitalarticles.dp("Zoroastrianism", finaltext)

# Everyday life (82 articles)", finaltext)

finaltext = vitalarticles.dp("Clothing", finaltext)
finaltext = vitalarticles.dp("Cooking", finaltext)
finaltext = vitalarticles.dp("Color", finaltext)
finaltext = vitalarticles.dp("Black", finaltext)
finaltext = vitalarticles.dp("White", finaltext)
finaltext = vitalarticles.dp("Emotion", finaltext)
finaltext = vitalarticles.dp("Anger", finaltext)
finaltext = vitalarticles.dp("Fear", finaltext)
finaltext = vitalarticles.dp("Love", finaltext)
finaltext = vitalarticles.dp("Happiness", finaltext)
finaltext = vitalarticles.dp("Family", finaltext)
finaltext = vitalarticles.dp("Adult", finaltext)
finaltext = vitalarticles.dp("Child", finaltext)
finaltext = vitalarticles.dp("Infant", finaltext)
finaltext = vitalarticles.dp("Marriage", finaltext)
finaltext = vitalarticles.dp("Gender", finaltext)
finaltext = vitalarticles.dp("Man", finaltext)
finaltext = vitalarticles.dp("Woman", finaltext)
finaltext = vitalarticles.dp("Mind", finaltext)
finaltext = vitalarticles.dp("Consciousness", finaltext)
finaltext = vitalarticles.dp("Thought", finaltext)
finaltext = vitalarticles.dp("Sleep", finaltext)
finaltext = vitalarticles.dp("Dream", finaltext)

# Food and drink", finaltext)

finaltext = vitalarticles.dp("Food", finaltext)
finaltext = vitalarticles.dp("Bread", finaltext)
finaltext = vitalarticles.dp("Cheese", finaltext)
finaltext = vitalarticles.dp("Fruit", finaltext)
finaltext = vitalarticles.dp("Grain", finaltext)
finaltext = vitalarticles.dp("Maize", finaltext)
finaltext = vitalarticles.dp("Meat", finaltext)
finaltext = vitalarticles.dp("Oat", finaltext)
finaltext = vitalarticles.dp("Potato", finaltext)
finaltext = vitalarticles.dp("Rice", finaltext)
finaltext = vitalarticles.dp("Soybean", finaltext)
finaltext = vitalarticles.dp("Vegetable", finaltext)
finaltext = vitalarticles.dp("Wheat", finaltext)
finaltext = vitalarticles.dp("Beer", finaltext)
finaltext = vitalarticles.dp("Coffee", finaltext)
finaltext = vitalarticles.dp("Drinking water", finaltext)
finaltext = vitalarticles.dp("Milk", finaltext)
finaltext = vitalarticles.dp("Tea", finaltext)
finaltext = vitalarticles.dp("Wine", finaltext)

# Language", finaltext)

finaltext = vitalarticles.dp("Language", finaltext)
finaltext = vitalarticles.dp("Alphabet", finaltext)
finaltext = vitalarticles.dp("Letter", finaltext)
finaltext = vitalarticles.dp("Grammar", finaltext)
finaltext = vitalarticles.dp("Word", finaltext)
finaltext = vitalarticles.dp("Writing", finaltext)
finaltext = vitalarticles.dp("Specific languages", finaltext)
finaltext = vitalarticles.dp("Arabic language", finaltext)
finaltext = vitalarticles.dp("Featured article Bengali language", finaltext)
finaltext = vitalarticles.dp("Chinese language", finaltext)
finaltext = vitalarticles.dp("English language", finaltext)
finaltext = vitalarticles.dp("French language", finaltext)
finaltext = vitalarticles.dp("German language", finaltext)
finaltext = vitalarticles.dp("Greek language", finaltext)
finaltext = vitalarticles.dp("Hindi", finaltext)
finaltext = vitalarticles.dp("Japanese language", finaltext)
finaltext = vitalarticles.dp("Latin", finaltext)
finaltext = vitalarticles.dp("Portuguese language", finaltext)
finaltext = vitalarticles.dp("Punjabi language", finaltext)
finaltext = vitalarticles.dp("Russian language", finaltext)
finaltext = vitalarticles.dp("Sanskrit", finaltext)
finaltext = vitalarticles.dp("Spanish language", finaltext)
finaltext = vitalarticles.dp("Swahili language", finaltext)

# Recreation and entertainment", finaltext)

finaltext = vitalarticles.dp("Recreation", finaltext)
finaltext = vitalarticles.dp("Game", finaltext)
finaltext = vitalarticles.dp("Board game", finaltext)
finaltext = vitalarticles.dp("Featured article Chess", finaltext)
finaltext = vitalarticles.dp("Draughts", finaltext)
finaltext = vitalarticles.dp("Go", finaltext)
finaltext = vitalarticles.dp("Mancala", finaltext)
finaltext = vitalarticles.dp("Video game", finaltext)
finaltext = vitalarticles.dp("Gambling", finaltext)
finaltext = vitalarticles.dp("Sport", finaltext)
finaltext = vitalarticles.dp("Featured article Association football (soccer)", finaltext)
finaltext = vitalarticles.dp("Athletics (track and field)", finaltext)
finaltext = vitalarticles.dp("Toy", finaltext)

# Society and social sciences (88 articles)", finaltext)

finaltext = vitalarticles.dp("Society", finaltext)
finaltext = vitalarticles.dp("Culture", finaltext)

# Social issues", finaltext)

finaltext = vitalarticles.dp("Abortion", finaltext)
finaltext = vitalarticles.dp("Euthanasia", finaltext)
finaltext = vitalarticles.dp("Suicide", finaltext)
finaltext = vitalarticles.dp("Discrimination", finaltext)
finaltext = vitalarticles.dp("Racism", finaltext)
finaltext = vitalarticles.dp("Sexism", finaltext)
finaltext = vitalarticles.dp("Education", finaltext)
finaltext = vitalarticles.dp("Freedom", finaltext)
finaltext = vitalarticles.dp("Slavery", finaltext)
finaltext = vitalarticles.dp("Globalization", finaltext)
finaltext = vitalarticles.dp("Featured article Law", finaltext)
finaltext = vitalarticles.dp("Capital punishment", finaltext)
finaltext = vitalarticles.dp("Civil rights", finaltext)
finaltext = vitalarticles.dp("Constitution", finaltext)
finaltext = vitalarticles.dp("Crime", finaltext)
finaltext = vitalarticles.dp("Justice", finaltext)
finaltext = vitalarticles.dp("Police", finaltext)
finaltext = vitalarticles.dp("Peace", finaltext)
finaltext = vitalarticles.dp("War", finaltext)
finaltext = vitalarticles.dp("Pollution", finaltext)
finaltext = vitalarticles.dp("Poverty", finaltext)
finaltext = vitalarticles.dp("Social movement", finaltext)
finaltext = vitalarticles.dp("Environmentalism", finaltext)
finaltext = vitalarticles.dp("Feminism", finaltext)

# Business and economics", finaltext)

finaltext = vitalarticles.dp("Business", finaltext)
finaltext = vitalarticles.dp("Economics", finaltext)
finaltext = vitalarticles.dp("Good", finaltext)
finaltext = vitalarticles.dp("Service (economics)", finaltext)
finaltext = vitalarticles.dp("Supply and demand", finaltext)
finaltext = vitalarticles.dp("Company", finaltext)
finaltext = vitalarticles.dp("Corporation", finaltext)
finaltext = vitalarticles.dp("Finance", finaltext)
finaltext = vitalarticles.dp("Industry", finaltext)
finaltext = vitalarticles.dp("Agriculture", finaltext)
finaltext = vitalarticles.dp("Manufacturing", finaltext)
finaltext = vitalarticles.dp("Mining", finaltext)
finaltext = vitalarticles.dp("Market", finaltext)
finaltext = vitalarticles.dp("Marketing", finaltext)
finaltext = vitalarticles.dp("Money", finaltext)
finaltext = vitalarticles.dp("Euro", finaltext)
finaltext = vitalarticles.dp("Japanese yen", finaltext)
finaltext = vitalarticles.dp("Pound sterling", finaltext)
finaltext = vitalarticles.dp("Renminbi", finaltext)
finaltext = vitalarticles.dp("United States dollar", finaltext)
finaltext = vitalarticles.dp("Tax", finaltext)
finaltext = vitalarticles.dp("Trade", finaltext)


# Media", finaltext)

finaltext = vitalarticles.dp("Advertising", finaltext)
finaltext = vitalarticles.dp("Broadcasting", finaltext)
finaltext = vitalarticles.dp("Journalism", finaltext)
finaltext = vitalarticles.dp("Magazine", finaltext)
finaltext = vitalarticles.dp("Mass media", finaltext)
finaltext = vitalarticles.dp("News", finaltext)
finaltext = vitalarticles.dp("Newspaper", finaltext)
finaltext = vitalarticles.dp("Publishing", finaltext)

# Politics and government", finaltext)

finaltext = vitalarticles.dp("Politics", finaltext)
finaltext = vitalarticles.dp("Government", finaltext)
finaltext = vitalarticles.dp("Capitalism", finaltext)
finaltext = vitalarticles.dp("Socialism", finaltext)
finaltext = vitalarticles.dp("Civics", finaltext)
finaltext = vitalarticles.dp("Anarchism", finaltext)
finaltext = vitalarticles.dp("Communism", finaltext)
finaltext = vitalarticles.dp("Democracy", finaltext)
finaltext = vitalarticles.dp("Dictatorship", finaltext)
finaltext = vitalarticles.dp("Fascism", finaltext)
finaltext = vitalarticles.dp("Monarchy", finaltext)
finaltext = vitalarticles.dp("Theocracy", finaltext)
finaltext = vitalarticles.dp("Conservatism", finaltext)
finaltext = vitalarticles.dp("Liberalism", finaltext)
finaltext = vitalarticles.dp("Diplomacy", finaltext)
finaltext = vitalarticles.dp("Imperialism", finaltext)
finaltext = vitalarticles.dp("Military", finaltext)
finaltext = vitalarticles.dp("Nationalism", finaltext)
finaltext = vitalarticles.dp("State", finaltext)
finaltext = vitalarticles.dp("Specific political and governmental institutions", finaltext)
finaltext = vitalarticles.dp("European Union", finaltext)
finaltext = vitalarticles.dp("International Red Cross and Red Crescent Movement", finaltext)
finaltext = vitalarticles.dp("NATO", finaltext)
finaltext = vitalarticles.dp("Nobel Prize", finaltext)
finaltext = vitalarticles.dp("OPEC", finaltext)
finaltext = vitalarticles.dp("United Nations", finaltext)
finaltext = vitalarticles.dp("World Health Organization", finaltext)
finaltext = vitalarticles.dp("World Trade Organization", finaltext)

# Social sciences", finaltext)

finaltext = vitalarticles.dp("Social sciences", finaltext)
finaltext = vitalarticles.dp("Anthropology", finaltext)
finaltext = vitalarticles.dp("Political science", finaltext)
finaltext = vitalarticles.dp("Psychology", finaltext)
finaltext = vitalarticles.dp("Sociology", finaltext)

# Health and medicine (48 articles)", finaltext)
# Disease", finaltext)

finaltext = vitalarticles.dp("Disease", finaltext)
finaltext = vitalarticles.dp("Featured article Alzheimer's disease", finaltext)
finaltext = vitalarticles.dp("Cancer", finaltext)
finaltext = vitalarticles.dp("Cholera", finaltext)
finaltext = vitalarticles.dp("Common cold", finaltext)
finaltext = vitalarticles.dp("Diabetes mellitus", finaltext)
finaltext = vitalarticles.dp("Dysentery", finaltext)
finaltext = vitalarticles.dp("Featured article Influenza", finaltext)
finaltext = vitalarticles.dp("Malaria", finaltext)
finaltext = vitalarticles.dp("Parkinson's disease", finaltext)
finaltext = vitalarticles.dp("Sexually transmitted disease", finaltext)
finaltext = vitalarticles.dp("AIDS", finaltext)
finaltext = vitalarticles.dp("Syphilis", finaltext)
finaltext = vitalarticles.dp("Smallpox", finaltext)
finaltext = vitalarticles.dp("Featured article Tuberculosis", finaltext)

# Health and fitness", finaltext)

finaltext = vitalarticles.dp("Health", finaltext)
finaltext = vitalarticles.dp("Physical fitness", finaltext)
finaltext = vitalarticles.dp("Exercise", finaltext)
finaltext = vitalarticles.dp("Hygiene", finaltext)
finaltext = vitalarticles.dp("Obesity", finaltext)
finaltext = vitalarticles.dp("Stress", finaltext)
finaltext = vitalarticles.dp("Addiction", finaltext)
finaltext = vitalarticles.dp("Drug", finaltext)
finaltext = vitalarticles.dp("Nutrition", finaltext)


# Medicine", finaltext)

finaltext = vitalarticles.dp("Medicine", finaltext)
finaltext = vitalarticles.dp("Birth control", finaltext)
finaltext = vitalarticles.dp("Coma", finaltext)
finaltext = vitalarticles.dp("Disability", finaltext)
finaltext = vitalarticles.dp("Featured article Autism", finaltext)
finaltext = vitalarticles.dp("Blindness", finaltext)
finaltext = vitalarticles.dp("Hearing impairment", finaltext)
finaltext = vitalarticles.dp("Mental illness", finaltext)
finaltext = vitalarticles.dp("Physical trauma", finaltext)
finaltext = vitalarticles.dp("Aneurysm", finaltext)
finaltext = vitalarticles.dp("Bone fracture", finaltext)
finaltext = vitalarticles.dp("Brain damage", finaltext)
finaltext = vitalarticles.dp("Burn", finaltext)
finaltext = vitalarticles.dp("Cardiac arrest", finaltext)
finaltext = vitalarticles.dp("Frostbite", finaltext)
finaltext = vitalarticles.dp("Bleeding", finaltext)
finaltext = vitalarticles.dp("Inflammation", finaltext)
finaltext = vitalarticles.dp("Respiratory failure", finaltext)
finaltext = vitalarticles.dp("Shock", finaltext)
finaltext = vitalarticles.dp("Stroke", finaltext)
finaltext = vitalarticles.dp("Medication", finaltext)
finaltext = vitalarticles.dp("Antibiotic", finaltext)
finaltext = vitalarticles.dp("Vaccine", finaltext)
finaltext = vitalarticles.dp("Physician", finaltext)

# Science (177 articles)", finaltext)

finaltext = vitalarticles.dp("Science", finaltext)
finaltext = vitalarticles.dp("History of science", finaltext)
finaltext = vitalarticles.dp("Nature", finaltext)
finaltext = vitalarticles.dp("Philosophy of science", finaltext)
finaltext = vitalarticles.dp("Scientific method", finaltext)

# Astronomy", finaltext)

finaltext = vitalarticles.dp("Astronomy", finaltext)
finaltext = vitalarticles.dp("Asteroid", finaltext)
finaltext = vitalarticles.dp("Featured article Big Bang", finaltext)
finaltext = vitalarticles.dp("Featured article Comet", finaltext)
finaltext = vitalarticles.dp("Eclipse", finaltext)
finaltext = vitalarticles.dp("Featured article Galaxy", finaltext)
finaltext = vitalarticles.dp("Milky Way", finaltext)
finaltext = vitalarticles.dp("Natural satellite", finaltext)
finaltext = vitalarticles.dp("Orbit", finaltext)
finaltext = vitalarticles.dp("Outer space", finaltext)
finaltext = vitalarticles.dp("Physical cosmology", finaltext)
finaltext = vitalarticles.dp("Featured article Planet", finaltext)
finaltext = vitalarticles.dp("Featured article Solar System", finaltext)
finaltext = vitalarticles.dp("Featured article Sun", finaltext)
finaltext = vitalarticles.dp("Featured article Mercury", finaltext)
finaltext = vitalarticles.dp("Featured article Venus", finaltext)
finaltext = vitalarticles.dp("Featured article Earth", finaltext)
finaltext = vitalarticles.dp("Featured article Moon", finaltext)
finaltext = vitalarticles.dp("Featured article Mars", finaltext)
finaltext = vitalarticles.dp("Featured article Asteroid belt", finaltext)
finaltext = vitalarticles.dp("Featured article Jupiter", finaltext)
finaltext = vitalarticles.dp("Featured article Saturn", finaltext)
finaltext = vitalarticles.dp("Featured article Uranus", finaltext)
finaltext = vitalarticles.dp("Featured article Neptune", finaltext)
finaltext = vitalarticles.dp("Featured article Star", finaltext)
finaltext = vitalarticles.dp("Featured article Supernova", finaltext)
finaltext = vitalarticles.dp("Universe", finaltext)

# Biology", finaltext)

finaltext = vitalarticles.dp("Biology", finaltext)
finaltext = vitalarticles.dp("Life", finaltext)
finaltext = vitalarticles.dp("Abiogenesis", finaltext)
finaltext = vitalarticles.dp("Anatomy", finaltext)
finaltext = vitalarticles.dp("Brain", finaltext)
finaltext = vitalarticles.dp("Gastrointestinal tract", finaltext)
finaltext = vitalarticles.dp("Heart", finaltext)
finaltext = vitalarticles.dp("Featured article Immune system", finaltext)
finaltext = vitalarticles.dp("Lung", finaltext)
finaltext = vitalarticles.dp("Skeleton", finaltext)
finaltext = vitalarticles.dp("Reproduction", finaltext)
finaltext = vitalarticles.dp("Pregnancy", finaltext)
finaltext = vitalarticles.dp("Sex", finaltext)
finaltext = vitalarticles.dp("Botany", finaltext)
finaltext = vitalarticles.dp("Cell (biology)", finaltext)
finaltext = vitalarticles.dp("Ecology", finaltext)
finaltext = vitalarticles.dp("Ecosystem", finaltext)
finaltext = vitalarticles.dp("Featured article Evolution", finaltext)
finaltext = vitalarticles.dp("Natural selection", finaltext)
finaltext = vitalarticles.dp("Featured article Genetics", finaltext)
finaltext = vitalarticles.dp("Featured article DNA", finaltext)
finaltext = vitalarticles.dp("Gene", finaltext)
finaltext = vitalarticles.dp("Heredity", finaltext)
finaltext = vitalarticles.dp("Organism", finaltext)
finaltext = vitalarticles.dp("Animal", finaltext)
finaltext = vitalarticles.dp("Amphibian", finaltext)
finaltext = vitalarticles.dp("Featured article Bird", finaltext)
finaltext = vitalarticles.dp("Featured article Dinosaur", finaltext)
finaltext = vitalarticles.dp("Fish", finaltext)
finaltext = vitalarticles.dp("Insect", finaltext)
finaltext = vitalarticles.dp("Mammal", finaltext)
finaltext = vitalarticles.dp("Cattle", finaltext)
finaltext = vitalarticles.dp("Cat", finaltext)
finaltext = vitalarticles.dp("Dog", finaltext)
finaltext = vitalarticles.dp("Horse", finaltext)
finaltext = vitalarticles.dp("Human", finaltext)
finaltext = vitalarticles.dp("Reptile", finaltext)
finaltext = vitalarticles.dp("Featured article Archaea", finaltext)
finaltext = vitalarticles.dp("Featured article Bacteria", finaltext)
finaltext = vitalarticles.dp("Fungus", finaltext)
finaltext = vitalarticles.dp("Plant", finaltext)
finaltext = vitalarticles.dp("Flower", finaltext)
finaltext = vitalarticles.dp("Tree", finaltext)
finaltext = vitalarticles.dp("Protist", finaltext)
finaltext = vitalarticles.dp("Species", finaltext)
finaltext = vitalarticles.dp("Zoology", finaltext)


# Chemistry", finaltext)

finaltext = vitalarticles.dp("Chemistry", finaltext)
finaltext = vitalarticles.dp("Biochemistry", finaltext)
finaltext = vitalarticles.dp("Organic chemistry", finaltext)
finaltext = vitalarticles.dp("Inorganic chemistry", finaltext)
finaltext = vitalarticles.dp("Acid", finaltext)
finaltext = vitalarticles.dp("Alloy", finaltext)
finaltext = vitalarticles.dp("Bronze", finaltext)
finaltext = vitalarticles.dp("Steel", finaltext)
finaltext = vitalarticles.dp("Featured article Atom", finaltext)
finaltext = vitalarticles.dp("Base", finaltext)
finaltext = vitalarticles.dp("Catalysis", finaltext)
finaltext = vitalarticles.dp("Chemical bond", finaltext)
finaltext = vitalarticles.dp("Chemical compound", finaltext)
finaltext = vitalarticles.dp("Alcohol", finaltext)
finaltext = vitalarticles.dp("Carbon dioxide", finaltext)
finaltext = vitalarticles.dp("Oil", finaltext)
finaltext = vitalarticles.dp("Salt", finaltext)
finaltext = vitalarticles.dp("Water", finaltext)
finaltext = vitalarticles.dp("Chemical element", finaltext)
finaltext = vitalarticles.dp("Aluminium", finaltext)
finaltext = vitalarticles.dp("Carbon", finaltext)
finaltext = vitalarticles.dp("Copper", finaltext)
finaltext = vitalarticles.dp("Gold", finaltext)
finaltext = vitalarticles.dp("Featured article Helium", finaltext)
finaltext = vitalarticles.dp("Featured article Hydrogen", finaltext)
finaltext = vitalarticles.dp("Iron", finaltext)
finaltext = vitalarticles.dp("Nitrogen", finaltext)
finaltext = vitalarticles.dp("Featured article Oxygen", finaltext)
finaltext = vitalarticles.dp("Silicon", finaltext)
finaltext = vitalarticles.dp("Silver", finaltext)
finaltext = vitalarticles.dp("Sulfur", finaltext)
finaltext = vitalarticles.dp("Featured article Uranium", finaltext)
finaltext = vitalarticles.dp("Chemical reaction", finaltext)
finaltext = vitalarticles.dp("Crystal", finaltext)
finaltext = vitalarticles.dp("Electrolysis", finaltext)
finaltext = vitalarticles.dp("Glass", finaltext)
finaltext = vitalarticles.dp("Ion", finaltext)
finaltext = vitalarticles.dp("Metal", finaltext)
finaltext = vitalarticles.dp("Mineral", finaltext)
finaltext = vitalarticles.dp("Molecule", finaltext)
finaltext = vitalarticles.dp("Periodic table", finaltext)

# Earth science", finaltext)

finaltext = vitalarticles.dp("Earth science", finaltext)
finaltext = vitalarticles.dp("History of Earth", finaltext)
finaltext = vitalarticles.dp("Geology", finaltext)
finaltext = vitalarticles.dp("Avalanche", finaltext)
finaltext = vitalarticles.dp("Crust", finaltext)
finaltext = vitalarticles.dp("Earthquake", finaltext)
finaltext = vitalarticles.dp("Erosion", finaltext)
finaltext = vitalarticles.dp("Geologic fault", finaltext)
finaltext = vitalarticles.dp("Magma", finaltext)
finaltext = vitalarticles.dp("Mantle", finaltext)
finaltext = vitalarticles.dp("Plate tectonics", finaltext)
finaltext = vitalarticles.dp("Volcano", finaltext)
finaltext = vitalarticles.dp("Earth's atmosphere", finaltext)
finaltext = vitalarticles.dp("Climate", finaltext)
finaltext = vitalarticles.dp("Cloud", finaltext)
finaltext = vitalarticles.dp("Flood", finaltext)
finaltext = vitalarticles.dp("Featured article Global warming", finaltext)
finaltext = vitalarticles.dp("Meteorology", finaltext)
finaltext = vitalarticles.dp("Rain", finaltext)
finaltext = vitalarticles.dp("Featured article Tornado", finaltext)
finaltext = vitalarticles.dp("Featured article Tropical cyclone", finaltext)
finaltext = vitalarticles.dp("Weather", finaltext)
finaltext = vitalarticles.dp("Oceanography", finaltext)

# Physics", finaltext)

finaltext = vitalarticles.dp("Physics", finaltext)
finaltext = vitalarticles.dp("Particle physics", finaltext)
finaltext = vitalarticles.dp("Standard Model", finaltext)
finaltext = vitalarticles.dp("Subatomic particle", finaltext)
finaltext = vitalarticles.dp("Electron", finaltext)
finaltext = vitalarticles.dp("Neutrino", finaltext)
finaltext = vitalarticles.dp("Neutron", finaltext)
finaltext = vitalarticles.dp("Featured article Photon", finaltext)
finaltext = vitalarticles.dp("Proton", finaltext)
finaltext = vitalarticles.dp("Classical mechanics", finaltext)
finaltext = vitalarticles.dp("Kinematics", finaltext)
finaltext = vitalarticles.dp("Kinetics", finaltext)
finaltext = vitalarticles.dp("Energy", finaltext)
finaltext = vitalarticles.dp("Kinetic energy", finaltext)
finaltext = vitalarticles.dp("Potential energy", finaltext)
finaltext = vitalarticles.dp("Force", finaltext)
finaltext = vitalarticles.dp("Electromagnetism", finaltext)
finaltext = vitalarticles.dp("Gravitation", finaltext)
finaltext = vitalarticles.dp("Strong interaction", finaltext)
finaltext = vitalarticles.dp("Weak interaction", finaltext)
finaltext = vitalarticles.dp("Heat", finaltext)
finaltext = vitalarticles.dp("Temperature", finaltext)
finaltext = vitalarticles.dp("Light", finaltext)
finaltext = vitalarticles.dp("Electromagnetic radiation", finaltext)
finaltext = vitalarticles.dp("Featured article Speed of light", finaltext)
finaltext = vitalarticles.dp("Visible spectrum", finaltext)
finaltext = vitalarticles.dp("Mass", finaltext)
finaltext = vitalarticles.dp("Weight", finaltext)
finaltext = vitalarticles.dp("Matter", finaltext)
finaltext = vitalarticles.dp("Motion", finaltext)
finaltext = vitalarticles.dp("Quantum mechanics", finaltext)
finaltext = vitalarticles.dp("Sound", finaltext)
finaltext = vitalarticles.dp("Space", finaltext)
finaltext = vitalarticles.dp("Thermodynamics", finaltext)
finaltext = vitalarticles.dp("Theory of relativity", finaltext)
finaltext = vitalarticles.dp("Time", finaltext)

# Technology (121 articles)", finaltext)

finaltext = vitalarticles.dp("Technology", finaltext)
finaltext = vitalarticles.dp("History of technology", finaltext)
finaltext = vitalarticles.dp("Engineering", finaltext)
finaltext = vitalarticles.dp("Artificial intelligence", finaltext)
finaltext = vitalarticles.dp("Biotechnology", finaltext)
finaltext = vitalarticles.dp("Genetic engineering", finaltext)
finaltext = vitalarticles.dp("Nuclear technology", finaltext)
finaltext = vitalarticles.dp("Tool", finaltext)

# Energy", finaltext)

finaltext = vitalarticles.dp("Electricity", finaltext)
finaltext = vitalarticles.dp("Geothermal power", finaltext)
finaltext = vitalarticles.dp("Hydropower", finaltext)
finaltext = vitalarticles.dp("Nuclear power", finaltext)
finaltext = vitalarticles.dp("Petroleum", finaltext)
finaltext = vitalarticles.dp("Solar energy", finaltext)
finaltext = vitalarticles.dp("Wind power", finaltext)

# Electronics", finaltext)

finaltext = vitalarticles.dp("Electronics", finaltext)
finaltext = vitalarticles.dp("Battery", finaltext)
finaltext = vitalarticles.dp("Capacitor", finaltext)
finaltext = vitalarticles.dp("Diode", finaltext)
finaltext = vitalarticles.dp("Incandescent light bulb", finaltext)
finaltext = vitalarticles.dp("Integrated circuit", finaltext)
finaltext = vitalarticles.dp("Semiconductor", finaltext)
finaltext = vitalarticles.dp("Transistor", finaltext)

# Mechanical and structural engineering", finaltext)

finaltext = vitalarticles.dp("Mechanical engineering", finaltext)
finaltext = vitalarticles.dp("Engine", finaltext)
finaltext = vitalarticles.dp("Electric motor", finaltext)
finaltext = vitalarticles.dp("Internal combustion engine", finaltext)
finaltext = vitalarticles.dp("Jet engine", finaltext)
finaltext = vitalarticles.dp("Steam engine", finaltext)
finaltext = vitalarticles.dp("Inclined plane", finaltext)
finaltext = vitalarticles.dp("Lever", finaltext)
finaltext = vitalarticles.dp("Pulley", finaltext)
finaltext = vitalarticles.dp("Robot", finaltext)
finaltext = vitalarticles.dp("Wheel", finaltext)
finaltext = vitalarticles.dp("Arch", finaltext)
finaltext = vitalarticles.dp("Bridge", finaltext)
finaltext = vitalarticles.dp("Canal", finaltext)
finaltext = vitalarticles.dp("Dam", finaltext)
finaltext = vitalarticles.dp("Dome", finaltext)
finaltext = vitalarticles.dp("House", finaltext)
finaltext = vitalarticles.dp("Pyramid", finaltext)
finaltext = vitalarticles.dp("Tower", finaltext)

# Transportation", finaltext)

finaltext = vitalarticles.dp("Transport", finaltext)
finaltext = vitalarticles.dp("Vehicle", finaltext)
finaltext = vitalarticles.dp("Aircraft", finaltext)
finaltext = vitalarticles.dp("Automobile", finaltext)
finaltext = vitalarticles.dp("Bicycle", finaltext)
finaltext = vitalarticles.dp("Elevator", finaltext)
finaltext = vitalarticles.dp("Helicopter", finaltext)
finaltext = vitalarticles.dp("Motorcycle", finaltext)
finaltext = vitalarticles.dp("Train", finaltext)

# Information technology", finaltext)

finaltext = vitalarticles.dp("Information technology", finaltext)
finaltext = vitalarticles.dp("Abacus", finaltext)
finaltext = vitalarticles.dp("Calculator", finaltext)
finaltext = vitalarticles.dp("Computer", finaltext)
finaltext = vitalarticles.dp("Featured article Cryptography", finaltext)


finaltext = vitalarticles.dp("Camera", finaltext)
finaltext = vitalarticles.dp("Glasses", finaltext)
finaltext = vitalarticles.dp("Laser", finaltext)
finaltext = vitalarticles.dp("Lens", finaltext)
finaltext = vitalarticles.dp("Microscope", finaltext)
finaltext = vitalarticles.dp("Prism", finaltext)
finaltext = vitalarticles.dp("Telescope", finaltext)
finaltext = vitalarticles.dp("Telecommunication", finaltext)
finaltext = vitalarticles.dp("E-mail", finaltext)
finaltext = vitalarticles.dp("Internet", finaltext)
finaltext = vitalarticles.dp("Microphone", finaltext)
finaltext = vitalarticles.dp("Mobile phone", finaltext)
finaltext = vitalarticles.dp("Printing press", finaltext)
#finaltext = vitalarticles.dp("Printing", finaltext                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
#finaltext = vitalarticles.dp("Radio", finaltext)
#
#finaltext = vitalarticles.dp("Telephone", finaltext)

#finaltext = vitalarticles.dp("Television", finaltext)
#finaltext = vitalarticles.dp("Typewriter", finaltext)
#finaltext = vitalarticles.dp("Video", finaltext)
#finaltext = vitalarticles.dp("World Wide Web", finaltext)
print 'Done!'
print 'Final Diff'
wikipedia.showDiff(vapage.get(), finaltext)
#vapage.put(wikitext, 'Updating ratings for articles')